### ISSUE TITLE
Support the upper village traffic study

### ISSUE THREAD

**Issue by bloombar** [croton-on-hudson/bicycle-pedestrian-committee#15]
## Description
The village has issued an RFP ([click to view](https://github.com/croton-on-hudson/bicycle-pedestrian-committee/files/2857600/Croton.RFP.-.Traffic.Engineering.-.Dummy.Light.pdf)) and is receiving proposals for a traffic study of the upper village around the dummy light.  It is hoped that this traffic study will help pedestrian issues around the dummy light (see Issue #6) as well as the school board's proposed reduced speed limit in the area of Maple St's crosswalk to PVC.

## Updates
* 16 April 2019 - in committee meeting, most agreed that having the study evaluate and recommend various solutions to the traffic problem, rather than simply analyze traffic at the intersection, would be a sensible idea.
* 8 February 2019 - The Gazette published a letter to the editor from local resident, Paul Steinberg, critical of the traffic light study and specifically of the Bicycle & Pedestrian committee.  [Full text is available from the Croton United blog](http://www.crotonunited.org/news-views/2019/2/8/is-crotons-beloved-dummy-light-in-jeopardy-of-extinction)
* 5 February 2019 - a committee member noted that the RFP issued by the village does not treat pedestrian crossings as the main focus of the study, and that the RFP seems "mostly about changing the dummy light to a regular traffic signal, which I feel is a distraction".
* 4 February 2019 - in the village board of trustees meeting, the agenda mentioned considering authorizing Simco Engineering to conduct the study for $6k.  A committee member circulated internally within the Bike/Ped committee her finding that that Simco Engineering is being investigated for various [corruption charges]( https://www.enr.com/articles/44380-in-hot-water-new-york-engineering-executives-charged-in-pay-to-play-scheme) by the Manhattan DA's office.  It's unclear whether the village knows about this.  At the board meeting, A committee member requested that the traffic study include the entrance/exit to/from Vassallo Park.  Apparently the traffic study was delayed for these or other reasons.
* 14 January 2019 - In committee meeting, the mayor says village has received bids on “Upper Village Traffic Study.” Village staff will be discussing an expanded traffic study w/ school board.
* 6 December 2018 - the Croton Board of Education approved [a resolution](http://www.boarddocs.com/ny/chufsd/Board.nsf/goto?open&id=B6YRD85F0658) calling for the village to pursue passive traffic calming strategies, and to expand the scope of the traffic study the village is planning to look into this.
* 19 September 2018 - at committee meeting, Mayor Pugh said the village will be drafting RFPs for a traffic study of the upper village.

**Comment by mlschuer** [comment]
Here is the traffic study. 
[19-008 Croton Upper Village Report 09.19.19.pdf](https://github.com/croton-on-hudson/bicycle-pedestrian-committee/files/5397435/19-008.Croton.Upper.Village.Report.09.19.19.pdf)
