### ISSUE TITLE
Paint sharrows on Elliott Way

### ISSUE THREAD

**Issue by bloombar** [croton-on-hudson/bicycle-pedestrian-committee#36]
## Description
Shared lane markings, also known as "sharrows", are painted stencils on the road surface that remind drivers and bicyclists that the road is shared.  This can give confidence and clarity to both cyclists and drivers.  

Due to confusing signage at Elliott Way, the committee has heard from several that it is currently unclear to bicyclists whether they should ride on the sidewalk or on the road.  Committee members believe painting sharrows on the road would make it clear to drivers and cyclists themselves that cyclists should ride on the road in that area.

Other areas of concern for cyclists, such as Maple St, Riverside, and elsewhere may also benefit.

## Considerations
- Stencils for these are cheap, and should be low cost to paint.
- See [our committee's research on sharrows](https://github.com/croton-on-hudson/bicycle-pedestrian-committee/wiki/Traffic-calming-techniques#shared-lane-markings-aka-sharrows).

## Updates
- 20 June 2019 - Committee agrees to write a letter to the village recommending painting sharrows at Elliott Way, and possibly other key streets in the upper village.  Some want to limit the request to just Elliott Way in order not to ask too much at once, while others think the idea that this is a big "ask" is ridiculous, given how simple they are to paint.  One guest at the meeting suggested that the village should not paint them if doing so would be overly expensive and controversial, since sharrows are intended to be cheap and easy.

- Sept 2019 - Sharrows have been painted on Eliot Way. BPC sent a letter to the Gazette thanking the village for doing so and telling readers what they mean and how to drive/ride their bikes around them.

- 26 August 2021 - MLS changed title of this card to limit to Eliot Way and close the issue. If committee wishes to raise additional areas for sharrows, we should make a new card. (There is a separate card for our request last summer of sharrows to the approach to PVC and crosswalks across Benedict.)

**Comment by mlschuer** [comment]
The sharrows have been painted
