### ISSUE TITLE
Monitor Half Moon Bay's compliance with public easement of the walk/bike trail

### ISSUE THREAD

**Issue by bloombar** [croton-on-hudson/bicycle-pedestrian-committee#41]
## Description
Surface condition and access to the walking/biking trail on the southern end of the Croton trail between Half Moon Bay and the Hudson.  It is currently closed, locked by a gate, despite the existence of a public easement to this trail that requires it to be accessible to the public.

## Considerations
* The slate surface has been uneven and non-ADA compliant for many years, at least since 2014, when BPC members noted it and took photos.
* Taking action on this issue is not in HMB's interests, since leaving it as-is is tantamount to privatising this public space for their residents.  The BPC should consider requesting the village to force HMB to resolve this problem.
* HMB has had compliance problems in the past.  Prior to 2010, they had signs on this portion of the trail stating it was only open to HMB residents.  The BPC and village requested they remove those signs because of the public easement, which they did.

## Photos
![IMG_7678](https://user-images.githubusercontent.com/2209098/61663631-f37cf480-acc8-11e9-8e7e-325e90483559.JPG)

## Updates
* 21 July 2019 - southern end of trail is closed, locked by a gate.  The sign states the reason is due to storm damage from a Hurricane... could they mean Hurricane Sandy in 2012?!

**Comment by mlschuer** [comment]
I am closing this idea and moving it to "completed" because it seems redundant with issue #39

**Comment by bloombar** [comment]
See related Half Moon Bay problems:
- #68 - bring entrance to promenade into ADA compliance
- #39 - improve pedestrian accessibility to promenade
- #9 - repave Half Moon Bay mixed-use path
