### ISSUE TITLE
Crosswalks along Benedict

### ISSUE THREAD

**Issue by mlschuer** [croton-on-hudson/bicycle-pedestrian-committee#64]
Persuade Village to add crosswalks across Benedict Boulevard  .. along with Ped Xing warning signs. 

## Updates
- 22 September 2022 - while one crosswalk does not solve the problem for the entire street, I am closing this issue for now since no other crosswalks seem likely in the near future.
- 24 May 2022 - Department of Public works has painted a crosswalk across Benedict at Hastings Ave. 
![image](https://user-images.githubusercontent.com/2209098/191763598-553e9e8e-902b-4d13-8f5a-6c641ba80b84.png)
- 31 January 2021 - BPC member A.B. drafted a few informal concept diagrams of potential crosswalk designs [available here](https://github.com/croton-on-hudson/bicycle-pedestrian-committee/tree/master/problem_areas/benedict_boulevard).
- June 2020 - at a Board of Trustees workshop session in June 2020, BPC Chairperson Matthew Schuerman asked the board to add crosswalks and ped-xing signs along Benedict at Young, Hastings, Penfield and Whelan for a variety of reasons:
    - It is a pedestrian-friendly area;
    - Benedict is a wide street with frequent speeding;
    - Benedict is along school bus routes and  children are expected to cross it in one direction or other at the beginning or end of the day to get to or from their school buses.

DPW Superintendent Frank Balbi said that he would look at adding one or two but that every time you add a crosswalk you also have to make sure you have the capacity to repaint them, and that currently, they try to repaint crosswalks once a year.

## Concept diagrams
Informal concept diagrams to show how a little bit of cheap paint on the street can solve the problem, if the will exists.
![crosswalk on benedict](https://github.com/croton-on-hudson/bicycle-pedestrian-committee/raw/master/problem_areas/benedict_boulevard/benedict_crosswalks.png)

![gottwald circle concept](https://github.com/croton-on-hudson/bicycle-pedestrian-committee/raw/master/problem_areas/benedict_boulevard/gotwald_circle_to_morningside.png)

**Comment by bloombar** [comment]
Note updates:
- as of 24 May 2022 - Department of Public Works (DPW) has painted a crosswalk across Benedict at Hastings Ave.
- as of January 2024 - DPW is planning to paint crosswalks at Gotwald Circle and has already placed new curb ramps for them (except those missing at Truesdale).  See #32 for details of the Gotwald Circle recommendations.
