### ISSUE TITLE
Eliminate parking spaces on Oneida Ave in front of Maracas restaurant that create a blind corner with S Riverside Ave

### ISSUE THREAD

**Issue by bloombar** [croton-on-hudson/bicycle-pedestrian-committee#76]
## Description
There are unnecessary parking spaces on Oneida Ave at the corner of S Riverside Ave (near the abandoned Maracas restaurant location).  These create a blind corner for cars making a turn around that corner.  Eliminate those spaces to create a safer turn.

**Comment by mlschuer** [comment]
Jan. 18, 2023: Mayor Pugh and Trustee Simon said that the two spaces had been eliminated.

**Comment by bloombar** [comment]
@mlschuer  ... am i remembering incorrectly that you asked Len to confirm this and he said that the spots at maracas had not been eliminated, but that a spot near the entrance to cappricio had been eliminated at the request of capriccio.

**Comment by mlschuer** [comment]
Yes. I went back and edited it—but maybe my changes did not save? Will fix. Matthew SchuermanJournalist/AuthorHe/him/hisMatthewSchuerman.comCell: (914) 398-8141On Jan 18, 2023, at 10:38 PM, bloombar ***@***.***> wrote:﻿
@mlschuer  ... am i remembering incorrectly that you asked Len to confirm this and he said that the spots at maracas had not been eliminated, but that a spot near the entrance to cappricio had been eliminated at the request of capriccio.

**Comment by bloombar** [comment]
Member RO sent photos of the completed repainting of the parking spots on South Riverside by Oneida, but the blind corner remains.

![Image](https://github.com/croton-on-hudson/bicycle-pedestrian-committee/assets/2209098/bcf4ae18-9ef8-4efb-9b9a-8020c06bd276)
![Image](https://github.com/croton-on-hudson/bicycle-pedestrian-committee/assets/2209098/2c601891-8596-42dd-863b-4d2c78f6d200)
![Image](https://github.com/croton-on-hudson/bicycle-pedestrian-committee/assets/2209098/50b2190f-2cd7-4d9d-acb2-6b7f91f65902)
![Image](https://github.com/croton-on-hudson/bicycle-pedestrian-committee/assets/2209098/69aca1d8-a094-4762-9283-8de517ba8480)
